blueprint:
  name: Weather — Forecast TTS (AI Optional)
  description: Announces weather forecasts and changes via TTS, with optional AI rephrasing for natural language.
  domain: automation
  source_url: https://github.com/zodyking/weather-forecast-alert-blueprint/blob/main/weather-forecast.yaml
  input:
    weather_entity:
      name: Weather Entity
      description: The weather entity in Home Assistant that provides current conditions and forecast data, including support for hourly and daily forecasts from services like OpenWeatherMap or similar integrations.
      selector:
        entity:
          domain: weather
    ai_task_entity:
      name: AI Task Entity (Optional)
      description: An optional AI task entity (such as a Google AI integration) used to rephrase the weather messages for more natural-sounding TTS output. Leave blank if not using AI rephrasing.
      selector:
        entity:
          domain: ai_task
      default: []
    tts_engine:
      name: TTS Engine
      description: The Text-to-Speech engine entity in Home Assistant responsible for generating spoken announcements, such as Piper TTS or Google Translate TTS.
      selector:
        entity:
          domain: tts
    speakers:
      name: Speakers
      description: The media player entities (e.g., speakers or smart displays) where the TTS announcements will be played. Multiple can be selected for broadcasting to different locations.
      selector:
        entity:
          domain: media_player
          multiple: true
    enable_time_based:
      name: Enable Time-Based Announcements
      description: Toggle to enable periodic weather announcements at set intervals during the day, based on the hour pattern, start time, and end time configurations.
      default: true
      selector:
        boolean: {}
    hour_pattern:
      name: Hour Pattern for Time-Based
      description: Specifies the interval for time-based announcements (e.g., '/3' for every 3 hours starting from the minute specified in the trigger). Only active if time-based announcements are enabled.
      default: /3
      selector:
        text: {}
    start_time:
      name: Start Time
      description: The earliest time of day (in HH:MM:SS format) when time-based announcements can occur. Announcements will only trigger between this and the end time.
      default: "08:00:00"
      selector:
        time: {}
    end_time:
      name: End Time
      description: The latest time of day (in HH:MM:SS format) when time-based announcements can occur. Announcements will only trigger between the start time and this time.
      default: "21:00:00"
      selector:
        time: {}
    enable_presence_triggered:
      name: Enable Presence-Triggered Announcements
      description: Toggle to enable weather announcements when presence is detected (e.g., someone arrives home), using the specified presence sensors.
      default: true
      selector:
        boolean: {}
    presence_sensors:
      name: Presence Sensors
      description: Binary sensor entities that detect presence (e.g., motion or occupancy sensors). Announcements trigger when these turn on if presence-triggered is enabled.
      selector:
        entity:
          domain: binary_sensor
          multiple: true
    enable_current_change_announce:
      name: Enable Current Change Announcements
      description: Toggle to enable announcements when the current weather condition changes (e.g., from sunny to rainy).
      default: true
      selector:
        boolean: {}
    enable_upcoming_change_announce:
      name: Enable Upcoming Change Announcements
      description: Toggle to enable announcements for upcoming weather changes, such as approaching precipitation, based on hourly forecasts and the minutes before announce setting.
      default: true
      selector:
        boolean: {}
    minutes_before_announce:
      name: Minutes Before Upcoming Announcement
      description: The number of minutes before an upcoming weather change (e.g., rain starting) that an announcement should be made. Used for upcoming change alerts.
      default: 5
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes
    precip_threshold:
      name: Precipitation Probability Threshold (%)
      description: The minimum precipitation probability percentage required to mention potential rain/snow in forecasts. Lower values include more mentions; higher values are more conservative.
      default: 30
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
trigger_variables:
  enable_time_based: !input enable_time_based
  enable_presence_triggered: !input enable_presence_triggered
  enable_current_change_announce: !input enable_current_change_announce
  enable_upcoming_change_announce: !input enable_upcoming_change_announce
  minutes_before_announce: !input minutes_before_announce
trigger:
  - trigger: time_pattern
    hours: !input hour_pattern
    minutes: "3"
    id: time_based
  - trigger: state
    entity_id: !input presence_sensors
    to: "on"
    id: presence_arrival
  - trigger: state
    entity_id: !input weather_entity
    id: current_change
  - trigger: time_pattern
    minutes: "/5"
    id: upcoming_change
condition:
  - condition: or
    conditions:
      - condition: and
        conditions:
          - condition: trigger
            id: time_based
          - condition: time
            after: !input start_time
            before: !input end_time
          - condition: template
            value_template: "{{ enable_time_based }}"
      - condition: and
        conditions:
          - condition: trigger
            id: presence_arrival
          - condition: template
            value_template: "{{ enable_presence_triggered }}"
      - condition: and
        conditions:
          - condition: trigger
            id: current_change
          - condition: template
            value_template: "{{ enable_current_change_announce }}"
      - condition: and
        conditions:
          - condition: trigger
            id: upcoming_change
          - condition: template
            value_template: "{{ enable_upcoming_change_announce }}"
action:
  - variables:
      key: !input weather_entity
      spoken: ""
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: time_based
              - condition: trigger
                id: presence_arrival
        sequence:
          - action: weather.get_forecasts
            target:
              entity_id: !input weather_entity
            data:
              type: daily
            response_variable: d
          - action: weather.get_forecasts
            target:
              entity_id: !input weather_entity
            data:
              type: hourly
            response_variable: h
          - variables:
              precip_threshold: !input precip_threshold
              hours_ahead: 24
              now_hour: "{{ now().hour }}"
              day_name: "{{ (now() | as_timestamp | timestamp_custom('%A', true)) }}"
              greeting: "{% if 5 <= now_hour <= 11 %}Good morning{% elif 12 <= now_hour <= 17 %} Good afternoon{% else %}Good evening{% endif %}"
              now_temp: "{{ state_attr(key,'temperature') }}"
              now_hum: "{{ state_attr(key,'humidity') }}"
              now_cond_h: "{% set s = (states(key) or '') | lower %} {% set s = s | replace('_',' ') | replace('-',' ') %} {% set s = s | replace('partlycloudy','partly cloudy') | replace('clearnight','clear night') %} {{ s | trim }}"
              daily_list: "{{ d.get(key,{}).get('forecast',[]) }}"
              today: "{{ daily_list[0] if daily_list|length>0 else dict() }}"
              high: "{{ today.get('temperature') }}"
              low: "{{ today.get('templow', today.get('temperature_low')) }}"
              today_cond_h: "{% set raw = (today.get('condition') or states(key) or '') | lower %} {% set s = raw | replace('_',' ') | replace('-',' ') %} {% set s = s | replace('partlycloudy','partly cloudy') | replace('clearnight','clear night') %} {{ s | trim }}"
              now_norm: "{{ now_cond_h | replace(' ','') }}"
              today_norm: "{{ today_cond_h | replace(' ','') }}"
              mention_expect: "{{ today_cond_h != '' and today_norm != now_norm }}"
              hourly_list: "{{ h.get(key,{}).get('forecast',[]) }}"
              next_hours: "{{ hourly_list[:hours_ahead] if hourly_list else [] }}"
              hits: "{{ (next_hours | selectattr('precipitation_probability','defined') | selectattr('precipitation_probability','ge', precip_threshold) | list) }}"
              first_hit: "{{ hits[0] if hits|length>0 else dict() }}"
              hit_pp: "{{ first_hit.get('precipitation_probability') }}"
              hit_cond_h: "{% set raw = (first_hit.get('condition','') | lower) %} {% set s = raw | replace('_',' ') | replace('-',' ') %} {% set s = s | replace('partlycloudy','partly cloudy') | replace('clearnight','clear night') %} {{ s | trim }}"
              hit_ts: "{% set t = none %} {% if first_hit.get('datetime') %} {% set t = as_datetime(first_hit.get('datetime')) | as_timestamp %} {% endif %} {{ t }}"
              hit_clock: "{% set out = '' %} {% if hit_ts is not none %} {% set out = (hit_ts | timestamp_custom('%I %p', true)) | replace(' 0',' ') %} {% endif %} {{ out }}"
              hit_hour_num: "{% set out = 0 %} {% if hit_ts is not none %} {% set out = (hit_ts | timestamp_custom('%H', true)) | int %} {% endif %} {{ out }}"
              hit_daypart: "{% set hnum = hit_hour_num %} {% if 5 <= hnum <= 11 %}this
