blueprint:
  name: Weather — Forecast TTS (AI Optional)
  description: |
    ![Weather Forecast Alerts banner](https://raw.githubusercontent.com/zodyking/weather-forecast-alert-blueprint/refs/heads/main/imageforecast.png)
    Speak a concise, TV-weatherman-style forecast to one or more speakers on a schedule.
    Pulls daily + hourly forecasts, mentions likely rain/snow with daypart and %, and (optionally) rewrites via an AI Task without changing facts.
    Tips:
    • Use a weather entity that supports `weather.get_forecasts` (daily + hourly).
    • Tune “Precipitation probability threshold” and “Hours ahead” to control precip mentions.
    • Turn off “Use AI rewrite” to speak the raw crafted message.
    • If your audio cuts in late, increase **TTS pre-roll (ms)** to give speakers time to wake up.
  domain: automation
  source_url: https://github.com/zodyking/weather-forecast-alert-blueprint/blob/main/weather-forecast.yaml
  input:
    weather_data:
      name: Weather Data
      description: This section allows you to select the primary weather entity that supplies current conditions and forecast information for generating announcements. Choose an entity compatible with Home Assistant's weather integrations, such as OpenWeatherMap, which supports both daily and hourly forecasts essential for detailed weather reports.
      icon: mdi:asterisk
      collapsed: true
      input:
        weather_entity:
          name: Weather Entity
          description: The weather entity in Home Assistant that provides current conditions and forecast data, including support for hourly and daily forecasts from services like OpenWeatherMap or similar integrations.
          default: ''
          selector:
            entity:
              domain: weather
    tts_settings:
      name: TTS Settings
      description: Configure the Text-to-Speech (TTS) system here, including the engine for voice synthesis, media players for output, voice selection, volume control, and pre-roll delay to ensure smooth audio playback. These settings determine how announcements are spoken and delivered through your smart home devices.
      icon: mdi:account-voice
      collapsed: true
      input:
        tts_engine:
          name: TTS Engine
          description: The Text-to-Speech engine entity in Home Assistant responsible for generating spoken announcements, such as Piper TTS or Google Translate TTS.
          default: ''
          selector:
            entity:
              domain: tts
        speakers:
          name: Speakers
          description: The media player entities (e.g., speakers or smart displays) where the TTS announcements will be played. Multiple can be selected for broadcasting to different locations.
          default: []
          selector:
            entity:
              domain: media_player
              multiple: true
        voice:
          name: TTS Voice
          description: The voice option for the TTS engine. Specify the voice identifier compatible with your TTS service.
          default: "en_US-carlin-high"
          selector:
            text: {}
        volume_level:
          name: Volume Level
          description: The volume level for announcements (range 0 to 1, where 1 is maximum volume).
          default: 0.6
          selector:
            number:
              min: 0
              max: 1
              step: 0.01
              mode: slider
        preroll_ms:
          name: TTS Pre-roll (ms)
          description: Delay in milliseconds before speaking to allow speakers time to wake up and avoid audio cutoff.
          default: 150
          selector:
            number:
              min: 0
              max: 1000
              step: 50
              unit_of_measurement: ms
    ai_settings:
      name: AI Rephrasing (Optional)
      description: This optional section enables AI-based rephrasing of weather messages for a more natural, professional tone, similar to a TV meteorologist. Select an AI task entity, toggle rephrasing on or off, and customize the prompt to guide how the AI rewrites messages while strictly preserving all factual details.
      icon: mdi:robot
      collapsed: true
      input:
        ai_task_entity:
          name: AI Task Entity (Optional)
          description: An optional AI task entity (such as a Google AI integration) used to rephrase the weather messages for more natural-sounding TTS output. Leave blank if not using AI rephrasing.
          selector:
            entity:
              domain: ai_task
          default: ''
        use_ai_rewrite:
          name: Use AI Rewrite
          description: Toggle to enable AI rephrasing of the weather messages. If disabled, the raw crafted message will be spoken directly.
          default: false
          selector:
            boolean: {}
        ai_rewrite_prompt:
          name: AI Rewrite Prompt
          description: The prompt template used for AI rephrasing. Customize this to adjust how the AI rewrites the message while preserving facts.
          default: "Rewrite the message below for clear, natural TTS in a crisp TV-meteorologist voice.\nHard rules:\n- Preserve every fact exactly: all numbers, units (degrees, %, mph), times, day names, and weather terms.\n- Do not invent, omit, reorder, round, or restate any facts. Keep original sequencing of info.\n- Output RAW TEXT ONLY — no quotes, code fences, YAML/JSON, greetings, preambles, or sign-offs.\n- 2–4 short sentences, ≤55 words, plain vocabulary, no emojis, no hashtags, no ALL CAPS.\n- If precipitation timing/probability exists, mention it once using the same daypart/time and %; otherwise omit.\n- Keep symbols and formatting as given (%, AM/PM). If the input is “Forecast not available.” return it unchanged.\n"
          selector:
            text:
              multiline: true
    time_based_settings:
      name: Time-Based Announcements
      description: Set up scheduled weather announcements that occur at regular intervals throughout the day. This section includes toggles for enabling the feature, patterns for timing (e.g., every few hours), start and end times to restrict announcements to specific periods, and day-of-week selections to limit when they trigger.
      icon: mdi:clock-outline
      collapsed: true
      input:
        enable_time_based:
          name: Enable Time-Based Announcements
          description: Toggle to enable periodic weather announcements at set intervals during the day, based on the hour pattern, start time, and end time configurations.
          default: true
          selector:
            boolean: {}
        hour_pattern:
          name: Hour Pattern for Time-Based
          description: Specifies the interval for time-based announcements (e.g., 'Hourly' for every hour).
          default: /3
          selector:
            select:
              options:
                - label: Hourly
                  value: /1
                - label: Every 2 Hours
                  value: /2
                - label: Every 3 Hours
                  value: /3
                - label: Every 4 Hours
                  value: /4
                - label: Every 5 Hours
                  value: /5
                - label: Every 6 Hours
                  value: /6
        minute_offset:
          name: Minute Offset
          description: The minute of the hour when the announcement should trigger (0-59).
          default: "3"
          selector:
            select:
              options:
                - label: "0"
                  value: "0"
                - label: "1"
                  value: "1"
                - label: "2"
                  value: "2"
                - label: "3"
                  value: "3"
