blueprint:
  name: Weather — Forecast TTS (AI Optional)
  description: Announces weather forecasts and changes via TTS, with optional AI rephrasing for natural language.
  domain: automation
  input:
    weather_entity:
      name: Weather Entity
      description: The weather entity providing forecasts.
      selector:
        entity:
          domain: weather
    ai_task_entity:
      name: AI Task Entity (Optional)
      description: Entity for AI message rephrasing (e.g., Google AI task).
      selector:
        entity:
          domain: ai_task
      default: []
    tts_engine:
      name: TTS Engine
      description: The TTS service to use for announcements.
      selector:
        entity:
          domain: tts
    speakers:
      name: Speakers
      description: Media players to announce on.
      selector:
        entity:
          domain: media_player
          multiple: true
    enable_time_based:
      name: Enable Time-Based Announcements
      description: Announce forecasts at regular intervals.
      default: true
      selector:
        boolean: {}
    hour_pattern:
      name: Hour Pattern for Time-Based
      description: Time pattern for announcements (e.g., /3 for every 3 hours).
      default: /3
      selector:
        text: {}
    start_time:
      name: Start Time
      description: Start time for time-based announcements.
      default: "08:00:00"
      selector:
        time: {}
    end_time:
      name: End Time
      description: End time for time-based announcements.
      default: "21:00:00"
      selector:
        time: {}
    enable_presence_triggered:
      name: Enable Presence-Triggered Announcements
      description: Announce on arrival (via presence sensors).
      default: true
      selector:
        boolean: {}
    presence_sensors:
      name: Presence Sensors
      description: Binary sensors for presence detection.
      selector:
        entity:
          domain: binary_sensor
          multiple: true
    enable_current_change_announce:
      name: Enable Current Change Announcements
      default: true
      selector:
        boolean: {}
    enable_upcoming_change_announce:
      name: Enable Upcoming Change Announcements
      default: true
      selector:
        boolean: {}
    minutes_before_announce:
      name: Minutes Before Upcoming Announcement
      default: 5
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes
    precip_threshold:
      name: Precipitation Probability Threshold (%)
      description: Threshold for mentioning precipitation.
      default: 30
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
trigger_variables:
  enable_time_based: !input enable_time_based
  enable_presence_triggered: !input enable_presence_triggered
  enable_current_change_announce: !input enable_current_change_announce
  enable_upcoming_change_announce: !input enable_upcoming_change_announce
  minutes_before_announce: !input minutes_before_announce
trigger:
  - trigger: time_pattern
    hours: !input hour_pattern
    minutes: "3"
    id: time_based
  - trigger: state
    entity_id: !input presence_sensors
    to: "on"
    id: presence_arrival
  - trigger: state
    entity_id: !input weather_entity
    id: current_change
  - trigger: time_pattern
    minutes: "/5"
    id: upcoming_change
condition:
  - condition: or
    conditions:
      - condition: and
        conditions:
          - condition: trigger
            id: time_based
          - condition: time
            after: !input start_time
            before: !input end_time
          - condition: template
            value_template: "{{ enable_time_based }}"
      - condition: and
        conditions:
          - condition: trigger
            id: presence_arrival
          - condition: template
            value_template: "{{ enable_presence_triggered }}"
      - condition: and
        conditions:
          - condition: trigger
            id: current_change
          - condition: template
            value_template: "{{ enable_current_change_announce }}"
      - condition: and
        conditions:
          - condition: trigger
            id: upcoming_change
          - condition: template
            value_template: "{{ enable_upcoming_change_announce }}"
action:
  - variables:
      key: !input weather_entity
      spoken: ""
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: time_based
              - condition: trigger
                id: presence_arrival
        sequence:
          - action: weather.get_forecasts
            target:
              entity_id: !input weather_entity
            data:
              type: daily
            response_variable: d
          - action: weather.get_forecasts
            target:
              entity_id: !input weather_entity
            data:
              type: hourly
            response_variable: h
          - variables:
              precip_threshold: !input precip_threshold
              hours_ahead: 24
              now_hour: "{{ now().hour }}"
              day_name: "{{ (now() | as_timestamp | timestamp_custom('%A', true)) }}"
              greeting: "{% if 5 <= now_hour <= 11 %}Good morning{% elif 12 <= now_hour <= 17 %} Good afternoon{% else %}Good evening{% endif %}"
              now_temp: "{{ state_attr(key,'temperature') }}"
              now_hum: "{{ state_attr(key,'humidity') }}"
              now_cond_h: "{% set s = (states(key) or '') | lower %} {% set s = s | replace('_',' ') | replace('-',' ') %} {% set s = s | replace('partlycloudy','partly cloudy') | replace('clearnight','clear night') %} {{ s | trim }}"
              daily_list: "{{ d.get(key,{}).get('forecast',[]) }}"
              today: "{{ daily_list[0] if daily_list|length>0 else dict() }}"
              high: "{{ today.get('temperature') }}"
              low: "{{ today.get('templow', today.get('temperature_low')) }}"
              today_cond_h: "{% set raw = (today.get('condition') or states(key) or '') | lower %} {% set s = raw | replace('_',' ') | replace('-',' ') %} {% set s = s | replace('partlycloudy','partly cloudy') | replace('clearnight','clear night') %} {{ s | trim }}"
              now_norm: "{{ now_cond_h | replace(' ','') }}"
              today_norm: "{{ today_cond_h | replace(' ','') }}"
              mention_expect: "{{ today_cond_h != '' and today_norm != now_norm }}"
              hourly_list: "{{ h.get(key,{}).get('forecast',[]) }}"
              next_hours: "{{ hourly_list[:hours_ahead] if hourly_list else [] }}"
              hits: "{{ (next_hours | selectattr('precipitation_probability','defined') | selectattr('precipitation_probability','ge', precip_threshold) | list) }}"
              first_hit: "{{ hits[0] if hits|length>0 else dict() }}"
              hit_pp: "{{ first_hit.get('precipitation_probability') }}"
              hit_cond_h: "{% set raw = (first_hit.get('condition','') | lower) %} {% set s = raw | replace('_',' ') | replace('-',' ') %} {% set s = s | replace('partlycloudy','partly cloudy') | replace('clearnight','clear night') %} {{ s | trim }}"
              hit_ts: "{% set t = none %} {% if first_hit.get('datetime') %} {% set t = as_datetime(first_hit.get('datetime')) | as_timestamp %} {% endif %} {{ t }}"
              hit_clock: "{% set out = '' %} {% if hit_ts is not none %} {% set out = (hit_ts | timestamp_custom('%I %p', true)) | replace(' 0',' ') %} {% endif %} {{ out }}"
              hit_hour_num: "{% set out = 0 %} {% if hit_ts is not none %} {% set out = (hit_ts | timestamp_custom('%H', true)) | int %} {% endif %} {{ out }}"
              hit_daypart: "{% set hnum = hit_hour_num %} {% if 5 <= hnum <= 11 %}this morning{% elif 12 <= hnum <= 17 %}this afternoon {% elif 18 <= hnum <= 22 %}this evening{% else %}overnight{% endif %}"
              precip_kind: "{% if 'snow' in hit_cond_h %}snow{% elif 'sleet' in hit_cond_h or 'hail' in hit_cond_h %}mixed precipitation {% elif hit_cond_h %}rain{% else %}precipitation{% endif %}"
              msg: "{% set p = [] %} {% set p = p + [greeting ~ '! ' ~ day_name ~ \"'s forecast.\"] %} {% set now_bits = [] %} {% if now_cond_h %}{% set now_bits = now_bits + [now_cond_h | capitalize] %}{% endif %} {% if now_temp is not none %}{% set now_bits = now_bits + [ (now_temp | round(0) ~ ' degrees') ] %}{% endif %} {% if now_hum is not none %}{% set now_bits = now_bits + [ ('humidity ' ~ now_hum ~ '%') ] %}{% endif %} {% if now_bits | length > 0 %}{% set p = p + ['Right now: ' ~ (now_bits | join(', ')) ~ '.'] %}{% endif %} {% set today_bits = [] %} {% if mention_expect %}{% set today_bits = today_bits + ['Expect ' ~ today_cond_h ~ '.'] %}{% endif %} {% if high is not none %}{% set today_bits = today_bits + ['High ' ~ (high | round(0)) ~ ' degrees.'] %}{% endif %} {% if low is not none %}{% set today_bits = today_bits + ['Low ' ~ (low | round(0)) ~ ' degrees.'] %}{% endif %} {% if today_bits | length > 0 %}{% set p = p + [ today_bits | join(' ') ] %}{% endif %} {% if hits | length > 0 and hit_pp is not none %} {% set phr = precip_kind ~ ' chances ' ~ hit_daypart %} {% if hit_clock %}{% set phr = phr ~ ' around ' ~ hit_clock %}{% endif %} {% set phr = phr ~ ': ' ~ (hit_pp | int) ~ '%.' %} {% set p = p + [ phr ] %} {% endif %} {{ p | join(' ') if p|length > 0 else 'Forecast not available.' }}"
              i_ai: true
              i_ai_task: !input ai_task_entity
              i_ai_text: "Rewrite the message below for clear, natural TTS in a crisp TV-meteorologist voice.\nHard rules:\n- Preserve every fact exactly: all numbers, units (degrees, %, mph), times, day names, and weather terms.\n- Do not invent, omit, reorder, round, or restate any facts. Keep original sequencing of info.\n- Output RAW TEXT ONLY — no quotes, code fences, YAML/JSON, greetings, preambles, or sign-offs.\n- 2–4 short sentences, ≤55 words, plain vocabulary, no emojis, no hashtags, no ALL CAPS.\n- If precipitation timing/probability exists, mention it once using the same daypart/time and %; otherwise omit.\n- Keep symbols and formatting as given (%, AM/PM). If the input is “Forecast not available.” return it unchanged.\n"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ i_ai and (i_ai_task | default('') | string) != '' }}"
                sequence:
                  - action: ai_task.generate_data
                    data:
                      entity_id: "{{ i_ai_task }}"
                      task_name: "weather message"
                      instructions: "{{ i_ai_text }}\nMessage:\n\"{{ msg | replace('\"','\\\\\"') }}\""
                    response_variable: aimsg
                  - variables:
                      spoken: "{{ aimsg.data | default(msg) }}"
            default:
              - variables:
                  spoken: "{{ msg }}"
      - conditions:
          - condition: trigger
            id: current_change
        sequence:
          - variables:
              now_cond_raw: "{{ trigger.to_state.state | lower }}"
              now_cond_h: "{% set s = now_cond_raw %} {% set s = s | replace('_',' ') | replace('-',' ') %} {% set s = s | replace('partlycloudy','partly cloudy') | replace('clearnight','clear night') %} {{ s | trim }}"
              from_cond_raw: "{{ trigger.from_state.state | default('unknown') | lower }}"
              is_change: "{{ now_cond_raw != from_cond_raw }}"
              msg: "Weather update: conditions have changed to {{ now_cond_h }}."
              i_ai: true
              i_ai_task: !input ai_task_entity
              i_ai_text: "Rewrite the message below for clear, natural TTS in a crisp TV-meteorologist voice.\nHard rules:\n- Preserve every fact exactly: all numbers, units (degrees, %, mph), times, day names, and weather terms.\n- Do not invent, omit, reorder, round, or restate any facts. Keep original sequencing of info.\n- Output RAW TEXT ONLY — no quotes, code fences, YAML/JSON, greetings, preambles, or sign-offs.\n- 2–4 short sentences, ≤55 words, plain vocabulary, no emojis, no hashtags, no ALL CAPS.\n- If precipitation timing/probability exists, mention it once using the same daypart/time and %; otherwise omit.\n- Keep symbols and formatting as given (%, AM/PM). If the input is “Forecast not available.” return it unchanged.\n"
          - if: "{{ is_change }}"
            then:
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ i_ai and (i_ai_task | default('') | string) != '' }}"
                    sequence:
                      - action: ai_task.generate_data
                        data:
                          entity_id: "{{ i_ai_task }}"
                          task_name: "weather message"
                          instructions: "{{ i_ai_text }}\nMessage:\n\"{{ msg | replace('\"','\\\\\"') }}\""
                        response_variable: aimsg
                      - variables:
                          spoken: "{{ aimsg.data | default(msg) }}"
                default:
                  - variables:
                      spoken: "{{ msg }}"
      - conditions:
          - condition: trigger
            id: upcoming_change
        sequence:
          - action: weather.get_forecasts
            target:
              entity_id: !input weather_entity
            data:
              type: hourly
            response_variable: h
          - variables:
              hourly_list: "{{ h.get(key,{}).get('forecast',[]) }}"
              upcoming: "{{ hourly_list | selectattr('datetime','gt', now().isoformat()) | sort(attribute='datetime') | list }}"
              next_hit: "{{ upcoming[0] if upcoming else {} }}"
              next_dt: "{{ next_hit.get('datetime') }}"
              next_ts: "{{ as_timestamp(next_dt) if next_dt else none }}"
              min_to: "{{ ((next_ts - as_timestamp(now())) / 60) | round(0) if next_ts else 0 }}"
              next_cond_raw: "{{ next_hit.get('condition','') | lower }}"
              next_cond_h: "{% set s = next_cond_raw %} {% set s = s | replace('_',' ') | replace('-',' ') %} {% set s = s | replace('partlycloudy','partly cloudy') | replace('clearnight','clear night') %} {{ s | trim }}"
              now_cond_raw: "{{ states(key) | lower }}"
              now_is_precip: "{{ 'rain' in now_cond_raw or 'snow' in now_cond_raw or 'hail' in now_cond_raw or 'pour' in now_cond_raw or 'lightning' in now_cond_raw }}"
              next_is_precip: "{{ 'rain' in next_cond_raw or 'snow' in next_cond_raw or 'hail' in next_cond_raw or 'pour' in next_cond_raw or 'lightning' in next_cond_raw }}"
              should_announce: "{{ next_ts is not none and next_is_precip and not now_is_precip and 0 < min_to <= minutes_before_announce }}"
              precip_kind: "{% if 'snow' in next_cond_h %}snow{% elif 'sleet' in next_cond_h or 'hail' in next_cond_h %}mixed precipitation {% elif next_cond_h %}rain{% else %}precipitation{% endif %}"
              msg: "Weather alert: {{ precip_kind }} expected in about {{ min_to }} minutes."
              i_ai: true
              i_ai_task: !input ai_task_entity
              i_ai_text: "Rewrite the message below for clear, natural TTS in a crisp TV-meteorologist voice.\nHard rules:\n- Preserve every fact exactly: all numbers, units (degrees, %, mph), times, day names, and weather terms.\n- Do not invent, omit, reorder, round, or restate any facts. Keep original sequencing of info.\n- Output RAW TEXT ONLY — no quotes, code fences, YAML/JSON, greetings, preambles, or sign-offs.\n- 2–4 short sentences, ≤55 words, plain vocabulary, no emojis, no hashtags, no ALL CAPS.\n- If precipitation timing/probability exists, mention it once using the same daypart/time and %; otherwise omit.\n- Keep symbols and formatting as given (%, AM/PM). If the input is “Forecast not available.” return it unchanged.\n"
          - if: "{{ should_announce }}"
            then:
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ i_ai and (i_ai_task | default('') | string) != '' }}"
                    sequence:
                      - action: ai_task.generate_data
                        data:
                          entity_id: "{{ i_ai_task }}"
                          task_name: "weather message"
                          instructions: "{{ i_ai_text }}\nMessage:\n\"{{ msg | replace('\"','\\\\\"') }}\""
                        response_variable: aimsg
                      - variables:
                          spoken: "{{ aimsg.data | default(msg) }}"
                default:
                  - variables:
                      spoken: "{{ msg }}"
  - if: "{{ spoken | default('') | trim != '' }}"
    then:
      - action: media_player.volume_set
        target:
          entity_id: !input speakers
        data:
          volume_level: 0.6
      - repeat:
          for_each: !input speakers
          sequence:
            - delay:
                milliseconds: 150
            - action: tts.speak
              target:
                entity_id: !input tts_engine
              data:
                cache: true
                media_player_entity_id: "{{ repeat.item }}"
                message: "{{ spoken | trim }}"
                options:
                  voice: "en_US-carlin-high"
mode: single
